tarape/views/account.py
from flask import (Blueprint, 
                   request, 
                   render_template, 
                   redirect, 
                   url_for,
                   current_app,
                   Flask)
from tarape import models
from tarape import oauth2
from flask_login import (UserMixin, 
                        login_required, 
                        current_user,
                        logout_user)

from werkzeug.security import generate_password_hash, check_password_hash

import datetime

module = Blueprint('accounts', __name__, url_prefix='/')

@module.route('/login')
def login():
    # print('>>>',current_user.is_authenticated)
    if current_user.is_authenticated:
        # print('hello')
        return redirect(url_for('dashboard.index'))
    return render_template('/account/login.html')
    
@module.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('accounts.login'))

tarape/views/dashboard.py
from flask import (Blueprint, 
                   request, 
                   render_template, 
                   redirect, 
                   url_for,
                   current_app,
                   Flask)
from tarape import models
from tarape import oauth2
# from tarape.forms import LoginForm, RegisterForm
from flask_login import (UserMixin, 
                        login_required, 
                        current_user)

from werkzeug.security import generate_password_hash, check_password_hash
# from flask import Flask, redirect, url_for, session, request, jsonify

import datetime


module = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@module.route('/')
@login_required
def index():
    # return render_template('/dashboard/index.html', user=current_user)
    return redirect(url_for('bulls.mybull'))
    

tarape/templates/dashboard/index.html
{% extends "base/base_layout.html" %}
{% include "base/nav.html" %}
{% block main %}
	Hello {{ user.firstname }}
	<br><br>
	<a href="{{ url_for('accounts.logout')}}">logout</a>
	
	<div id="example">
		<p>Original message: "{{ '{{ message }}' }}"</p>
		<p>Computed reversed message: "{{ '{{ reversedMessage }}' }}"</p>
	  </div>
{% endblock %}
{% block additional_js %}
<script type="text/javascript">
var vm = new Vue({
  el: '#example',
  data: {
    message: 'Hello'
  },
  computed: {
    // a computed getter
    reversedMessage: function () {
      // `this` points to the vm instance
      return this.message.split('').reverse().join('')
    }
  }
});
console.log('hello');
</script>
{% endblock %}